version: "3"

dotenv: ['.env']

silent: true

########################################################################################################################
#
# TOC
#
########################################################################################################################
#
# 1. MISCELLANEOUS
#
########################################################################################################################

tasks:
  ######################################################################################################################
  #
  #  1. MISCELLANEOUS
  #
  ######################################################################################################################

  dc:down:
    desc: Cleanup Devcontainer including volumes
    cmds:
      - docker-compose
        -f .devcontainer/docker-compose.yml
        down --volumes
